defaults:
  env:
    apiKey: secret:api_key #Replace this secret with your own secret
  resources:
    instance-type: C5
jobs:
  CloneRepo:
    inputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/gradient-ai/fashionmnist.git
  TrainModel:
    env:
      MODEL_DIR: /my-trained-model
    needs:
      - CloneRepo
    inputs:
      repo:
        type: volume
    outputs:
      trained-model:
        type: dataset
        with:
          id: dsrvw1m30ymhiyt #Replace this id with your own dataset id
    uses: container@v1
    with:
      args:
        - bash
        - "-c"
        - >-
          cd /inputs/repo/train && python train.py && cp -R /my-trained-model /outputs/trained-model
      image: 'tensorflow/tensorflow:1.9.0'
  UploadModel:
    inputs:
      model: TrainModel.outputs.trained-model
    outputs:
      model-id:
        type: string
    needs:
      - TrainModel
    uses: create-model@v1
    with:
      name: trained-model
      type: Tensorflow
